apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: vip
spec:
  agentArgs:
    - --disable-apiserver-lb=false
  agents: 2
  clusterCIDR: 172.16.0.0/17
  clusterDNS: 172.16.128.10
  mode: shared # virtual
  serverArgs:
    - --egress-selector-mode=disabled
  servers: 3
  serviceCIDR: 172.16.128.0/18
  version: v1.29.15
